import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const rootDirectory = path.dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/Pavel-mik/obsidian-spherical-graph
*/
`;

const inlineWorkerPlugin = {
	name: 'inline-spherical-graph-worker',
	setup(build) {
		const workers = new Map([
			['virtual:spherical-graph-worker', 'src/layout/worker-entry.ts'],
			['virtual:spherical-graph-data-worker', 'src/graph/graph-worker-entry.ts'],
			['virtual:spherical-graph-land-worker', 'src/render/land-worker-entry.ts'],
			['virtual:spherical-graph-geography-worker', 'src/geography/geography-worker-entry.ts'],
		]);
		build.onResolve(
			{ filter: /^virtual:spherical-graph-(?:worker|data-worker|land-worker|geography-worker)$/ },
			(args) => ({
				path: args.path,
				namespace: 'spherical-graph-worker',
			}),
		);

		build.onLoad(
			{
				filter: /.*/,
				namespace: 'spherical-graph-worker',
			},
			async (args) => {
				const entryPoint = workers.get(args.path);
				if (entryPoint === undefined) {
					throw new Error(`Unknown inline worker: ${args.path}`);
				}
				const result = await esbuild.build({
					absWorkingDir: rootDirectory,
					entryPoints: [entryPoint],
					bundle: true,
					format: 'iife',
					platform: 'browser',
					target: 'es2021',
					write: false,
					minify: prod,
					sourcemap: false,
					treeShaking: true,
					metafile: true,
					logLevel: 'silent',
				});

				const workerOutput = result.outputFiles[0];
				if (!workerOutput) {
					throw new Error('The inline layout worker produced no output.');
				}

				const watchFiles = Object.keys(result.metafile.inputs).map(
					(input) => path.resolve(rootDirectory, input),
				);

				return {
					contents: `export default ${JSON.stringify(workerOutput.text)};`,
					loader: 'js',
					watchFiles,
				};
			},
		);
	},
};

const context = await esbuild.context({
	absWorkingDir: rootDirectory,
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [inlineWorkerPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
